### ISSUE TITLE
Description for "GPU Model" needs to mention caveats

### ISSUE THREAD

**Issue by openjck** [mozilla/ensemble-transposer#86]
This issue was originally [filed against the Hardware Report](https://github.com/mozilla/firefox-hardware-report/issues/11) with this description:

> The description for "GPU Model" is misleading.
> The report only sees one GPU for users (whatever is first in `environment.system.gfx.adapters`), which may not be complete.
>
> E.g. for me, i see only deviceId:0x0d26 (built-in Intel Iris Pro) in Telemetry.
> However, my MB Pro actually has a GeForce GT 750M.
> [webgl](http://webglreport.com/?v=2) actually sees the GT750M and presumably uses it for accelerated rendering.
>
> We should call out that the hardware report is not representative for accelerated graphics at the moment.

I reached out to Georg, who still believes that we should do this. See [the original issue](https://github.com/mozilla/firefox-hardware-report/issues/11) for more information.

**Comment by SuYoungHong** [comment]
great for calling this out @openjck . 

What are thoughts on revising the copy to below: 


```
	GPU Model

"Share of primary Models GPUs."

"Note, this report only includes the primary GPU for each machine. Any supplemental GPUs are not included and this report is not representative of accelerated graphics."


	GPU Vendor

"Intel makes up the largest part of the desktop GPU market, accounting for over 60% of our release Desktop population. AMD and Nvidia come in at 2nd and 3rd."

"Since 2016, we see that Intel has increased their share as well, going from about 60% to 66% while AMD and Nvidia both dropped from around 18% to around 14%."

"Note, this report only includes the primary GPU for each machine. Any supplemental GPUs are not included and this report is not representative of accelerated graphics."

```
